# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-12-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160909_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=80000, verbose_name='文章内容'),
        ),
    ]
