# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='status',
            field=models.IntegerField(choices=[(0, '已读'), (-1, '未读')], verbose_name='状态'),
        ),
    ]
