# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-13 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activate',
            old_name='username',
            new_name='user',
        ),
    ]
