# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-09-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160919_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '开启'), (-1, '关闭')], verbose_name='状态'),
        ),
    ]
